version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: chaosdb
      POSTGRES_USER: chaos
      POSTGRES_PASSWORD: chaos
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://chaos:chaos@db:5432/chaosdb
      JWT_SECRET: change_this_secret
      PORT: 3000
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - '3001:80'

volumes:
  db_data: {}
